version: '3.5'


services:
  postgres:
    container_name: postgres_demo
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local